import { Injectable } from '@angular/core';

@Injectable()
export class MockProvider {
//dataList=[];
  getData(): any[] {
    // return mock data synchronously
    let data: any[] = [];
    for (var i = 0; i < 20; i++) {
      data.push( this._getRandomData() );
    }
    return data;
  }

  getAsyncData(): Promise<any[]> {
    // async receive mock data
    return new Promise(resolve => {

      setTimeout(() => {
        resolve(this.getData());
      }, 1000);

    });
  }

  private _getRandomData() {
    //let i = Math.floor( Math.random() * this._data.length );
    //return this.dataList;

    let i = Math.floor( Math.random() * this._data.length );
    return this._data[i];

  }

  private _data = [
    {
        "comment_id": "13",
        "comment_unit_id": "2",
        "comment_by": "1",
        "comment_subject": "Test",
        "comment_remark": "Test",
        "comment_priority": "0",
        "time_ago": "4 days ago",
        "comment_date": "2018-04-19 14:36:00",
        "comment_date_formatted": "Thu 19/04/2018, 02:36 PM",
        "duration": "1",
        "serviced_created_name": "Guest",
        "serviced_created_name_hastag": "(@denyov2)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/denyo_2018-03-13_050358.png",
        "comment_by_name": "Guest",
        "comment_by_name_hastag": "(@denyov2)",
        "comment_resources": "",
        "event_type": "C"
    },
    {
        "serviced_datetime_formatted": "Wed 28/03/2018 11:02 AM",
        "next_service_date_selected_date": "0000-00-00",
        "next_service_date_selected": "0",
        "service_id": "36",
        "service_unitid": "2",
        "serviced_by": "1",
        "serviced_datetime": "",
        "serviced_schduled_date": "2018-03-28",
        "serviced_scheduled_display": "Wed 28/03/2018, 11:02 AM",
        "serviced_datetime_edit": "2018-03-28T11:02:44",
        "duration": "1",
        "service_subject": "Ad-hoc Service",
        "service_remark": "Adhoc",
        "service_description": "",
        "is_denyo_support": "0",
        "service_priority": "0",
        "current_datetime": "28 Mar 2018",
        "is_request": "0",
        "created_by": "1",
        "next_service_date": "0000-00-00",
        "next_service_date_mobileview": "30/11/-0001",
        "nxtserviceformatted": "30 Nov -0001",
        "currentdate_mobileview": "28 Mar 2018",
        "service_status": "1",
        "serviced_created_name": "Guest",
        "serviced_created_name_hastag": "(@denyov2)",
        "serviced_created_name_hastag_withinclosedbracket": "(@denyov2)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/denyo_2018-03-13_050358.png",
        "serviced_by_name": "Guest",
        "serviced_by_name_hastag": "(@denyov2)",
        "serviced_by_name_hastag_withinclosedbracket": "(@denyov2)",
        "service_resources": "",
        "event_type": "S"
    },
    {
        "serviced_datetime_formatted": "Wed 28/03/2018 10:36 AM",
        "next_service_date_selected_date": "0000-00-00",
        "next_service_date_selected": "0",
        "service_id": "34",
        "service_unitid": "2",
        "serviced_by": "1",
        "serviced_datetime": "",
        "serviced_schduled_date": "2018-03-28",
        "serviced_scheduled_display": "Wed 28/03/2018, 10:36 AM",
        "serviced_datetime_edit": "2018-03-28T10:36:24",
        "duration": "1",
        "service_subject": "Ad-hoc Service",
        "service_remark": "Tezti",
        "service_description": "",
        "is_denyo_support": "0",
        "service_priority": "0",
        "current_datetime": "28 Mar 2018",
        "is_request": "0",
        "created_by": "1",
        "next_service_date": "0000-00-00",
        "next_service_date_mobileview": "30/11/-0001",
        "nxtserviceformatted": "30 Nov -0001",
        "currentdate_mobileview": "28 Mar 2018",
        "service_status": "1",
        "serviced_created_name": "Guest",
        "serviced_created_name_hastag": "(@denyov2)",
        "serviced_created_name_hastag_withinclosedbracket": "(@denyov2)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/denyo_2018-03-13_050358.png",
        "serviced_by_name": "Guest",
        "serviced_by_name_hastag": "(@denyov2)",
        "serviced_by_name_hastag_withinclosedbracket": "(@denyov2)",
        "service_resources": "23|2018228103439_123_1522213479873.jpg#-#24|2018228103456_123_1522213496059.jpg#-#25|2018228103510_123_1522213510164.jpg#-#26|2018228103526_123_1522213526799.jpg",
        "event_type": "S"
    },
    {
        "serviced_datetime_formatted": "Tue 27/03/2018 12:57 PM",
        "next_service_date_selected_date": "0000-00-00",
        "next_service_date_selected": "0",
        "service_id": "33",
        "service_unitid": "2",
        "serviced_by": "3",
        "serviced_datetime": "",
        "serviced_schduled_date": "2018-03-27",
        "serviced_scheduled_display": "Tue 27/03/2018, 12:57 PM",
        "serviced_datetime_edit": "2018-03-27T12:57:04",
        "duration": "1",
        "service_subject": "Ad-hoc Service",
        "service_remark": "New sensor",
        "service_description": "",
        "is_denyo_support": "0",
        "service_priority": "0",
        "current_datetime": "27 Mar 2018",
        "is_request": "0",
        "created_by": "3",
        "next_service_date": "0000-00-00",
        "next_service_date_mobileview": "30/11/-0001",
        "nxtserviceformatted": "30 Nov -0001",
        "currentdate_mobileview": "27 Mar 2018",
        "service_status": "1",
        "serviced_created_name": "Chun Hsin",
        "serviced_created_name_hastag": "(@Lerkila)",
        "serviced_created_name_hastag_withinclosedbracket": "(@Lerkila)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/20180317152422_123_20170914163841_123_IMG_0210.jpg",
        "serviced_by_name": "Chun Hsin",
        "serviced_by_name_hastag": "(@Lerkila)",
        "serviced_by_name_hastag_withinclosedbracket": "(@Lerkila)",
        "service_resources": "22|2018227125659_123_1522126619405.jpg",
        "event_type": "S"
    },
    {
        "alarm_id": "264",
        "alarm_name": "Wrn Stop fail",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 26/03/2018, 08:48 AM",
        "alarm_priority": "2",
        "time_ago": "4 weeks ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "220",
        "alarm_name": "Wrn Fuel Theft",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Wed 21/03/2018, 01:44 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "207",
        "alarm_name": "Emergency Stop",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Wed 21/03/2018, 08:30 AM",
        "alarm_priority": "1",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_red_48.png",
        "event_type": "A"
    },
    {
        "comment_id": "8",
        "comment_unit_id": "2",
        "comment_by": "26",
        "comment_subject": "Cmt",
        "comment_remark": "Comment added to @Kent",
        "comment_priority": "0",
        "time_ago": "1 month ago",
        "comment_date": "2018-03-21 00:27:00",
        "comment_date_formatted": "Wed 21/03/2018, 12:27 AM",
        "duration": "1",
        "serviced_created_name": "Stridec",
        "serviced_created_name_hastag": "(@Stridectester)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/denyo_2018-03-21_010331.jpg",
        "comment_by_name": "Stridec",
        "comment_by_name_hastag": "(@Stridectester)",
        "comment_resources": "",
        "event_type": "C"
    },
    {
        "comment_id": "7",
        "comment_unit_id": "2",
        "comment_by": "26",
        "comment_subject": "Comment",
        "comment_remark": "@Kent to comment sending",
        "comment_priority": "0",
        "time_ago": "1 month ago",
        "comment_date": "2018-03-21 00:24:00",
        "comment_date_formatted": "Wed 21/03/2018, 12:24 AM",
        "duration": "1",
        "serviced_created_name": "Stridec",
        "serviced_created_name_hastag": "(@Stridectester)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/denyo_2018-03-21_010331.jpg",
        "comment_by_name": "Stridec",
        "comment_by_name_hastag": "(@Stridectester)",
        "comment_resources": "5|20182210240_123_1521572040902.jpg",
        "event_type": "C"
    },
    {
        "alarm_id": "185",
        "alarm_name": "Emergency Stop",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "Guest",
        "alarm_assigned_to": "Kent",
        "alarm_received_date": "Tue 20/03/2018, 04:33 PM",
        "alarm_priority": "1",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_red_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "173",
        "alarm_name": "Emergency Stop",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "Guest",
        "alarm_assigned_to": "Kent",
        "alarm_received_date": "Tue 20/03/2018, 03:15 PM",
        "alarm_priority": "1",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_red_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "172",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "Guest",
        "alarm_assigned_to": "Kent",
        "alarm_received_date": "Tue 20/03/2018, 03:12 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "serviced_datetime_formatted": "Mon 19/03/2018 02:58 PM",
        "next_service_date_selected_date": "0000-00-00",
        "next_service_date_selected": "0",
        "service_id": "23",
        "service_unitid": "2",
        "serviced_by": "3",
        "serviced_datetime": "",
        "serviced_schduled_date": "2018-03-19",
        "serviced_scheduled_display": "Mon 19/03/2018, 02:58 PM",
        "serviced_datetime_edit": "2018-03-19T14:58:09",
        "duration": "1",
        "service_subject": "Ad-hoc Service",
        "service_remark": "New card installed",
        "service_description": "",
        "is_denyo_support": "0",
        "service_priority": "0",
        "current_datetime": "19 Mar 2018",
        "is_request": "0",
        "created_by": "3",
        "next_service_date": "0000-00-00",
        "next_service_date_mobileview": "30/11/-0001",
        "nxtserviceformatted": "30 Nov -0001",
        "currentdate_mobileview": "19 Mar 2018",
        "service_status": "1",
        "serviced_created_name": "Chun Hsin",
        "serviced_created_name_hastag": "(@Lerkila)",
        "serviced_created_name_hastag_withinclosedbracket": "(@Lerkila)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/20180317152422_123_20170914163841_123_IMG_0210.jpg",
        "serviced_by_name": "Chun Hsin",
        "serviced_by_name_hastag": "(@Lerkila)",
        "serviced_by_name_hastag_withinclosedbracket": "(@Lerkila)",
        "service_resources": "9|2018219145755_123_1521442675083.jpg",
        "event_type": "S"
    },
    {
        "alarm_id": "168",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "Guest",
        "alarm_assigned_to": "Sin Yee",
        "alarm_received_date": "Mon 19/03/2018, 02:33 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "167",
        "alarm_name": "!*Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "Stridec",
        "alarm_assigned_to": "Guest",
        "alarm_received_date": "Mon 19/03/2018, 01:28 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "166",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 01:19 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "165",
        "alarm_name": "*Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 01:14 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "164",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:49 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "163",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:48 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "162",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:47 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "161",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:46 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "160",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:45 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "159",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:44 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "158",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:31 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "157",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:30 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "156",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:29 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "155",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:28 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "154",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:27 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "153",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:26 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "152",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:25 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "151",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:24 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "150",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:23 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "149",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:22 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "148",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:21 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "147",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:20 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "146",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:19 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "145",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:18 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "144",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:17 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "143",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:16 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "141",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:14 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "142",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:15 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "140",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:14 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "139",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:14 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "138",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:13 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "137",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:12 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "136",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:11 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "135",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:10 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "134",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:09 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "133",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:08 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "132",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:07 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "131",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:06 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "130",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:05 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "129",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:04 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "128",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:03 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "127",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 11:02 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "126",
        "alarm_name": "Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 09:42 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "serviced_datetime_formatted": "Mon 19/03/2018 09:40 AM",
        "next_service_date_selected_date": "0000-00-00",
        "next_service_date_selected": "0",
        "service_id": "22",
        "service_unitid": "2",
        "serviced_by": "3",
        "serviced_datetime": "",
        "serviced_schduled_date": "2018-03-19",
        "serviced_scheduled_display": "Mon 19/03/2018, 09:40 AM",
        "serviced_datetime_edit": "2018-03-19T09:40:07",
        "duration": "1",
        "service_subject": "Ad-hoc Service",
        "service_remark": "New sensor",
        "service_description": "",
        "is_denyo_support": "0",
        "service_priority": "0",
        "current_datetime": "19 Mar 2018",
        "is_request": "0",
        "created_by": "3",
        "next_service_date": "0000-00-00",
        "next_service_date_mobileview": "30/11/-0001",
        "nxtserviceformatted": "30 Nov -0001",
        "currentdate_mobileview": "19 Mar 2018",
        "service_status": "1",
        "serviced_created_name": "Chun Hsin",
        "serviced_created_name_hastag": "(@Lerkila)",
        "serviced_created_name_hastag_withinclosedbracket": "(@Lerkila)",
        "user_photo": "http://denyodev1.stridecdev.com/staffphotos/20180317152422_123_20170914163841_123_IMG_0210.jpg",
        "serviced_by_name": "Chun Hsin",
        "serviced_by_name_hastag": "(@Lerkila)",
        "serviced_by_name_hastag_withinclosedbracket": "(@Lerkila)",
        "service_resources": "8|20182199404_123_1521423604375.jpg",
        "event_type": "S"
    },
    {
        "alarm_id": "125",
        "alarm_name": "Emergenc",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 09:19 AM",
        "alarm_priority": "1",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_red_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "124",
        "alarm_name": "Emergency Stop",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 08:33 AM",
        "alarm_priority": "1",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_red_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "123",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 08:21 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "122",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 07:37 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "121",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 07:27 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "120",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 06:48 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "119",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 06:43 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "118",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 06:21 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "117",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 06:00 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "116",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 05:24 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "115",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 05:18 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "114",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 05:08 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "113",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 04:58 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "112",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 04:53 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "111",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 04:30 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "110",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 04:14 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "109",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 04:05 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "108",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 03:06 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "106",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:41 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "105",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:33 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "104",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:21 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "103",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:20 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "102",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:19 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "101",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:06 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "100",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 02:03 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "99",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 01:58 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "98",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 01:53 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "97",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Mon 19/03/2018, 12:33 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "96",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 11:18 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "95",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 10:53 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "94",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 10:26 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "93",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 10:00 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "92",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 09:47 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "91",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 09:25 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "90",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 08:51 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "89",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 08:04 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "88",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:59 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "87",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:35 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "86",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 06:28 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "85",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 05:49 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "84",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 05:05 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "83",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:59 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "82",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:57 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "81",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:37 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "80",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:31 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "79",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:17 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "78",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:15 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "77",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:10 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "76",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 03:32 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "75",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 03:01 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "74",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 02:38 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "73",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 02:13 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "72",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 02:08 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "71",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 01:49 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "70",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:53 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "69",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:44 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "68",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:17 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "67",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:13 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "66",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:04 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "65",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:01 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "64",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 11:33 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "63",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 11:18 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "62",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 11:03 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "61",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 11:01 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "60",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 10:57 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "59",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 10:38 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "58",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 09:48 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "57",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 09:03 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "56",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 08:45 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "55",
        "alarm_name": "Fls Fuel",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 08:26 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "54",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 08:20 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "53",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 08:19 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "52",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:58 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "51",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:55 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "50",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:50 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "49",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:35 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "48",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 07:15 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "47",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 06:50 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "46",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 06:40 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "45",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 06:39 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "44",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 06:21 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "43",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 05:42 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "42",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 05:27 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "41",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 05:06 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "40",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 05:04 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "39",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:46 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "38",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 04:23 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "37",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 03:57 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "36",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 03:41 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "35",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 03:14 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "34",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 02:59 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "33",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 02:52 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "32",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 02:07 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "31",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 01:42 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "30",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 01:16 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "29",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 01:15 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "28",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 01:12 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "27",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:59 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "26",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:55 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "25",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:39 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "23",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sun 18/03/2018, 12:32 AM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "22",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 11:41 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "21",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 11:15 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "20",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 11:14 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "19",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 11:11 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "18",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 11:09 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "17",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 11:07 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "16",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 10:13 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "15",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 09:59 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "14",
        "alarm_name": "Wrn Fuel",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 09:56 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "13",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 09:50 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "12",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 09:45 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "11",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 09:41 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "10",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 08:18 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "9",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 07:05 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "8",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 06:59 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "7",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 06:57 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "6",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 06:56 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "5",
        "alarm_name": "!*Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 06:23 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "3",
        "alarm_name": "Fls Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 05:42 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    },
    {
        "alarm_id": "4",
        "alarm_name": "!*Wrn Fuel Level",
        "alarm_unit_id": "2",
        "alarm_assigned_by": "",
        "alarm_assigned_to": "",
        "alarm_received_date": "Sat 17/03/2018, 05:42 PM",
        "alarm_priority": "2",
        "time_ago": "1 month ago",
        "user_photo": "http://denyodev1.stridecdev.com/images/alert_yellow_48.png",
        "event_type": "A"
    }
];

}